### ISSUE TITLE
extension is unable to compile with PHP Version 7.2.15

### ISSUE THREAD

**Issue by Govind13100** [VirgilSecurity/sample-backend-php#1]
Hi there, 

I have tried everything that is said to do to install extension, but when i run php composer update there is a warning :

![compile](https://user-images.githubusercontent.com/26818036/57188928-04696580-6f25-11e9-9488-9f1ec19cccc4.png)

is there anyone to help ?

**Comment by PetrenkoAnton** [comment]
Hi @Govind13100

Judging to the log you have modules incompatibility.
What version of Windows and xampp do you use?
I will try to reproduce your issue and fix it via extension's update.

**Comment by Govind13100** [comment]
Window 7 
PHP version 7.2.15
Xamp/Apache version : 2.4.38

**Comment by Govind13100** [comment]
@PetrenkoAnton Hi,

Downgrading to version 5.6 , it still not working :(

**Comment by PetrenkoAnton** [comment]
@Govind13100
Our extension is build with NTS (Non Thread Safety).
It is enable only if you use mod_fastcgi.
But Xampp on Win use mod_php.

Now I am working on fixing this issue.
I will report the result tomorrow.

**Comment by Govind13100** [comment]
Okay! thanks. 

Will be waiting :)

**Comment by Govind13100** [comment]
@PetrenkoAnton  Should i use some other localhost, like WAMP, it will work there ?

**Comment by PetrenkoAnton** [comment]
@Govind13100 
You can try to use another local Win webserver, but need to setup fastcgi and php-nts.
Or use docker with ubuntu, nginx and php-fpm.

 I am working on fixing this issue. It will be resolved by soon.

**Comment by PetrenkoAnton** [comment]
@Govind13100 Hi!

Sorry for delay.

We are preparing the release with the issue’s fix (NTS errors with PHP7.2 for the Win webservers). 
Also we add support for PHP7.3. 
This may take a couple more days.

  I will report here.

  Thanks

**Comment by PetrenkoAnton** [comment]
@Govind13100  Hi!

Sorry for delay.

We updated the crypto library to version 2.6.3 and added PHP7.3 support.

There are .dll files for the Windows (PHP7.2 / 7.3) in the attachment.
Please update them on your local webserver according to your PHP version.

Thanks

[virgil_crypto_php.zip](https://github.com/VirgilSecurity/sample-backend-php/files/3178723/virgil_crypto_php.zip)

**Comment by Govind13100** [comment]
Hi there, really thanks for the zip file and your efforts, let me download and check if it's working or not. Thank you

**Comment by Govind13100** [comment]
That's great, the ext is enabled on 7.2. Thanks again

**Comment by Viggoleinen** [comment]
Hi,

Carl here!

Confirmed extension is located here:
/opt/cpanel/ea-php73/root/usr/lib64/php/modules

Confirmed extension=virgil_crypto_php.so was added to this php.ini:
/opt/cpanel/ea-php73/root/etc/php.ini

I have also added extension=virgil_crypto_php.so to public_html/php.ini

I found this error_log, seems like there is a problem with version `GLIBC_2.14’?

[24-May-2019 16:12:42 UTC] PHP Warning: PHP Startup: Unable to load dynamic library 'virgil_crypto_php.so
' (tried: /opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so
(/lib64/libc.so
.6: version `GLIBC_2.14' not found (required by /opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so
)), /opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so.so
(/opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so.so
: cannot open shared object file: No such file or directory)) in Unknown on line 0
