### ISSUE TITLE
How to use the authentication and JWT endpoint

### ISSUE THREAD

**Issue by Govind13100** [VirgilSecurity/sample-backend-php#2]
Hi there, 

I have installed it but when i try to excess the authentication endpoint, it's not working. Even the JWT endpoint. How can i use those to generate JWT token ?

**Comment by Govind13100** [comment]
![Screenshot](https://user-images.githubusercontent.com/26818036/57871743-aba0a380-7827-11e9-990b-c54dbc5e73aa.png)

this is what showing when i try to run

**Comment by PetrenkoAnton** [comment]
@Govind13100 Hi!

Seems like you have problems with the configuration of your local webserver.
Do you have access to the index page?

What endpoint shows 404 error (Page Not Found)?
Please show me the full url at your browser.

What is your current environment? Win/xampp/php7.2?
I am planning to go thru full flow (on your env) and show you correct and working steps.

Maybe I need to renew the README and add more info?
Thanks

**Comment by Govind13100** [comment]
![image](https://user-images.githubusercontent.com/26818036/57943456-b889c980-78f1-11e9-9fa4-4a9c869b30f2.png)

current environment:Win/xampp/ PHP Version 7.2.18
I am planning to go thru full flow (on your env) and show you correct and working steps.
--> yes that would really help

Maybe I need to renew the README and add more info?
Yes, actually when i run the Slim Web server , it throws the below error 

![image](https://user-images.githubusercontent.com/26818036/57943705-57162a80-78f2-11e9-9835-efd6cd61458d.png)

and when i solve this error, its throws below error 

![image](https://user-images.githubusercontent.com/26818036/57943776-90e73100-78f2-11e9-9af0-1bb01ddc81b9.png)

And when i try /authenticate

![image](https://user-images.githubusercontent.com/26818036/57943814-abb9a580-78f2-11e9-91df-d6b671ead7b1.png)

I have also tried it with Postman, but no positive result. What should i do here ?

**Comment by PetrenkoAnton** [comment]
@Govind13100 , You have configuration problems with your local web server.

I am planing to prepare step-by-step guide for you and publish it here. 
Also I will update the README file based on it.

ETA: current weekend.

Thanks

**Comment by Govind13100** [comment]
Hi there @PetrenkoAnton, thanks for you support, i will be waiting

**Comment by Govind13100** [comment]
Hi @PetrenkoAnton , any update for the whole flow ?

**Comment by PetrenkoAnton** [comment]
Hi @Govind13100 !
In a few hours, I am preparing screenshots for you now.

Sorry for delay

**Comment by Govind13100** [comment]
@PetrenkoAnton , I really appreciate :)

**Comment by PetrenkoAnton** [comment]
@Govind13100 

In my case, I installed xampp on the **D:\\** drive and used **sample-backend-php** domain.

There are few steps to configure **xampp**:

1. Add subfolder **sample-backend-php** into the **htdocs**

![01](https://user-images.githubusercontent.com/24354013/58041951-114fa100-7b42-11e9-8d81-1d9014b785f1.PNG)

2. Update **hosts** file

```
127.0.0.1 www.sample-backend-php
127.0.0.1 sample-backend-php
```

![02](https://user-images.githubusercontent.com/24354013/58042180-a5216d00-7b42-11e9-979b-acf1aa3cc79f.PNG)

3. Update **httpd-vhosts.conf** file:

```
<VirtualHost *:80>
    ServerAdmin admin@example.com
    DocumentRoot "D:/xampp/htdocs/sample-backend-php/app/public"
    ServerName sample-backend-php
    ServerAlias www.sample-backend-php
    ErrorLog "logs/sample-backend-php-error.log"
    CustomLog "logs/sample-backend-php-access.log" common
</VirtualHost>

```
![03](https://user-images.githubusercontent.com/24354013/58042635-e6fee300-7b43-11e9-8f30-cfa9a9831f3c.PNG)

4. Clone repository into the **sample-backend-php** folder:

`git clone git@github.com:VirgilSecurity/sample-backend-php.git .`

![04](https://user-images.githubusercontent.com/24354013/58042724-17468180-7b44-11e9-8caf-d7c59b1e91d1.PNG)

5. Install dependencies:

`composer install`

![05](https://user-images.githubusercontent.com/24354013/58042763-2decd880-7b44-11e9-8da8-fcdb24cd88fa.PNG)

6. Add **.htaccess** file into the **public** folder:

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

![06](https://user-images.githubusercontent.com/24354013/58042952-a6ec3000-7b44-11e9-8feb-8fc26d7ec9cb.PNG)

7. Add **.env** file from the **.env.example** file:

`copy .env.example .env`

![07](https://user-images.githubusercontent.com/24354013/58043005-d26f1a80-7b44-11e9-92df-3b5af35fa470.PNG)

8. Create application at the [Virgil Dashboard](https://dashboard.virgilsecurity.com):

![08](https://user-images.githubusercontent.com/24354013/58043124-13672f00-7b45-11e9-8a67-03aa531f2d90.PNG)

9. Generate and get configuration file:

![09](https://user-images.githubusercontent.com/24354013/58043153-237f0e80-7b45-11e9-874c-e5043e2b7d01.PNG)

![10](https://user-images.githubusercontent.com/24354013/58043169-2e39a380-7b45-11e9-9528-1d1c41746efc.PNG)

10. Paste credentials into the **.env**-file

![11](https://user-images.githubusercontent.com/24354013/58043221-49a4ae80-7b45-11e9-9cae-c6ac325397b9.PNG)

11. Try to use [Postman](https://www.getpostman.com/) (or other clients) to call API endpoints:

- /authenticate (POST)

![12](https://user-images.githubusercontent.com/24354013/58043284-78bb2000-7b45-11e9-8567-68c31d79ae76.PNG)

- /virgil-jwt (GET)

![13](https://user-images.githubusercontent.com/24354013/58043353-9b4d3900-7b45-11e9-8c1a-970ff8d2c315.PNG)

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,
Feel free to contact me If you have any problems with this guide.

Thanks

**Comment by Govind13100** [comment]
Hi, okay i am able to generate token at my localhost. But now i need it to move to my server (cpanel), how can i configure there ?

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,
You must understand that this is a sample (without a lot of checks and etc).
Do you want to use it in your production?

I updated the  README file, please check.

First of all, run **[virgil-test.php](https://github.com/VirgilSecurity/sample-backend-php/blob/master/_help/virgil-test.php)** file on your remote server and paste the output here.

Thanks

**Comment by Govind13100** [comment]
Yes i want to use it in production.

And here is the output 

array(6) { ["EXTENSION"]=> string(17) "virgil_crypto_php" ["IS_EXTENSION_LOADED"]=> bool(false) ["OS"]=> string(5) "Linux" ["PHP"]=> string(3) "5.6" ["PATH_TO_EXTENSIONS_DIR"]=> string(47) "/opt/cpanel/ea-php56/root/usr/lib64/php/modules" ["PATH_TO_PHP.INI"]=> string(37) "/opt/cpanel/ea-php56/root/etc/php.ini" }

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,

You need to update PHP version to the 7.2 or 7.3.
And run again the **virgil-test.php** file.

After that, go thru updated README file.

Let me know if you will have problems with it.

Thanks

**Comment by Govind13100** [comment]
@PetrenkoAnton okay thanks

**Comment by Govind13100** [comment]
Hi @PetrenkoAnton 

The hosting company didn’t manage to make the extension work. Can you please check if it has compatibility with CloudLinux PHP package?

server is running on cloudlinux and here is their reply:

We have checked the issue and did a lot of work around. However, the issue is still here.
The possible reason is CloudLinux with own repo for the packages:

Please can you let me know if it has compatibility with CloudLinux PHP packages.

Thanks.

**Comment by PetrenkoAnton** [comment]
@Govind13100 Hi!

Do you have access to the current directory?
`/opt/cpanel/ea-php72/root/usr/lib64/php/modules`

And can you change the current file?
`/opt/cpanel/ea-php72/root/etc/php.ini`

Also you need to be able to restart your server.

Maybe [this guide](https://docs.cloudlinux.com/php_selector/#compiling-your-own-extensions) can help you (but start from the step 5).

[Here](https://github.com/VirgilSecurity/sample-backend-php#extension-installation-example) is my example with the Linux OS, nginx webserver and php-fpm.

Please try this steps and show me the output (screenshots).

Thanks

**Comment by Govind13100** [comment]
hi @PetrenkoAnton 

Do you have access to the current directory?
/opt/cpanel/ea-php73/root/usr/lib64/php/modules

—> Yes the extension was added there.

And can you change the current file?
/opt/cpanel/ea-php72/root/etc/php.ini

—> Yes php.ini was updated.

Also you need to be able to restart your server.

—> Yes server was updated.

I even had my hosting company do this for me and after much work from their end with no success, they said “Please contact the developer of extension in order to check if it has compatibility with CloudLinux”.

Does the virgil_crypto_php extension have compatibility with CloudLinux, which is installed on my server? Can you please confirm that before I try more?

Thanks

“Here is my example with the Linux OS, nginx webserver and php-fpm.”
—> I’m not sure if you posted your example?

**Comment by PetrenkoAnton** [comment]
@Govind13100 Hi!

Please show me the output of the *virgil_test.php* file after this steps:

<img width="373" alt="Screen Shot 2019-05-28 at 12 57 22 PM" src="https://user-images.githubusercontent.com/24354013/58469472-3e0a4680-8148-11e9-8039-308d904d4de2.png">

And please show me the first screen of the *phpinfo();*
I need to know full name and current version of the server's OS to reproduce your issue.

Thanks

**Comment by Govind13100** [comment]
https://www.crn-solutions.com/virgil-test.php

here is the url you see the output and php info here...

**Comment by Govind13100** [comment]
![screencapture-crn-solutions-virgil-test-php-2019-05-28-15_39_57](https://user-images.githubusercontent.com/26818036/58470291-fa6f0700-815e-11e9-86a3-8d04071dac2a.png)

**Comment by PetrenkoAnton** [comment]
@Govind13100  , 
Extension is not loaded.

Today I will try to reproduce your environment on the CL.
And if necessary, I will correct the extension's file or send a sh-script to add the extension to the CL server.

Thanks

**Comment by Govind13100** [comment]
okay thanks, i will be waiting, is there any other way to use this virgil security feature in php website ?

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,
First of all, you need to setup our crypto-extension.
Today I will deal with this issue and will post the result.

Thanks

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,

Please, check the right paths according to your PHP version.

<img width="577" alt="Screen Shot 2019-05-28 at 4 49 49 PM" src="https://user-images.githubusercontent.com/24354013/58483288-b123b500-8168-11e9-9462-aba48809f68e.png">

<img width="548" alt="Screen Shot 2019-05-28 at 4 42 56 PM" src="https://user-images.githubusercontent.com/24354013/58483562-3018ed80-8169-11e9-8fa4-fd8e06f5251e.png">

Please, try again to setup extension correctly.

Let me know if the issue is still here?

Thanks

**Comment by carlno** [comment]
Hi!

Yes, the issue is still there.

Confirmed extension is located here:
/opt/cpanel/ea-php73/root/usr/lib64/php/modules

Confirmed extension=virgil_crypto_php.so was added to this php.ini:
/opt/cpanel/ea-php73/root/etc/php.ini

I have also added extension=virgil_crypto_php.so to public_html/php.ini

I found this error_log, seems like there is a problem with version `GLIBC_2.14’?

[24-May-2019 16:12:42 UTC] PHP Warning: PHP Startup: Unable to load dynamic library 'virgil_crypto_php.so
' (tried: /opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so
(/lib64/libc.so
.6: version `GLIBC_2.14' not found (required by /opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so
)), /opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so.so
(/opt/cpanel/ea-php73/root/usr/lib64/php/modules/virgil_crypto_php.so.so
: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by PetrenkoAnton** [comment]
@Viggoleinen , Hi!

Thanks for locating the error via error_log. It will help us to fix this issue.
I think there are some problems with the non-installed required libs on your server OS.
Tomorrow I will consult with other our developers and give you an answer how to fix.

Thanks a lot!

**Comment by carlno** [comment]
@PetrenkoAnton Thanks. Looking forward to it!

**Comment by PetrenkoAnton** [comment]
@Viggoleinen , what version of the CentOS do you use?

Seems like that on the current CentOS lacks one of the libs.

Now we are fixing this issue.
As soon as there will be a result - I will publish here.

Thanks

**Comment by PetrenkoAnton** [comment]
@Viggoleinen ,
Please run
`ldd --version`
and show me the output

Thanks

**Comment by carlno** [comment]
@PetrenkoAnton 
Hi,
Our server is "CloudLinux Server release 6.10" and ldd --version:
ldd (GNU libc) 2.12
Thanks

**Comment by PetrenkoAnton** [comment]
@Viggoleinen Hi!

Please try to use this extension (it has been compiled for PHP 7.3 and GLIBC 2.12):
[virgil_crypto_php.so.zip](https://github.com/VirgilSecurity/sample-backend-php/files/3247164/virgil_crypto_php.so.zip)

Thanks

**Comment by carlno** [comment]
@PetrenkoAnton 
Thanks, I will give it a try and let you know the outcome!

**Comment by carlno** [comment]
I just wanted to ask, you don't recommend me to instead update GLIBC? I'm not familiar with what that is and perhaps updating it will affect other things on our server...

**Comment by PetrenkoAnton** [comment]
@Viggoleinen 

In this case, all of our  customers who uses CloudLinux would have to update GLIBC.
We are trying to create the most compatible extensions to the most environments.

Thanks

**Comment by carlno** [comment]
@PetrenkoAnton 

OK, sounds very good. I can confirm that the new extension did the trick! Although we haven't tried it out yet, it is loaded and everything looks fine. Thanks for quick support!

Only one question: my phpinfo file shows “Low-level API support: disabled” - is that OK?

virgil_crypto_php
Version 	2.6.3
Low-level API support 	disabled

**Comment by PetrenkoAnton** [comment]
@Viggoleinen 

Yes, this is correct:

<img width="978" alt="Screen Shot 2019-06-06 at 1 07 26 PM" src="https://user-images.githubusercontent.com/24354013/59025102-16a82d80-885c-11e9-9a7c-dba4096ceee3.png">

We are going to add this fixes to the new patch release.

Thanks for your reply!

**Comment by carlno** [comment]
Thanks!

**Comment by carlno** [comment]
...one more thing: What permission should be set for virgil_crypto_php.so? Other extensions seems to have 755, but this one is set to something else.

**Comment by PetrenkoAnton** [comment]
@Viggoleinen , 

In my case permission for the virgil_crypto_php.so is:
<img width="463" alt="Screen Shot 2019-06-06 at 8 49 39 PM" src="https://user-images.githubusercontent.com/24354013/59054685-e2089600-889c-11e9-89c3-2c82bda1223f.png">

Please, try to generate your JWT.

Thanks

**Comment by Govind13100** [comment]
Hi there, 

i have tried with https://github.com/VirgilSecurity/sample-backend-php#authenticate-endpoint, but the response is not found, i know it;s something my end, but i followed you steps , by cloning the app and then composer install >> composer update >> upload to online server >> and then tried to hit the authenticate endpoint, but no positive result, it says, 404 error, Can you please help me out here ?

**Comment by PetrenkoAnton** [comment]
@Govind13100 , Hi!

Make sure that all your requests are going to the **./app/public/index.php**

Please check [this guide](https://www.slimframework.com/docs/v3/start/web-servers.html) according to your webserver.

Thanks

**Comment by Govind13100** [comment]
@PetrenkoAnton 

I have just performed : https://github.com/VirgilSecurity/sample-backend-php#clone-the-repository-and-install-dependencies

and then uploaded to my online server (cPanel)

all you code is in /sample-backend-php

so i am fetching the response using www.mydomain.com/sample-backend-php, this is my base url. 

Do i have to set the default access rule /to sample-backend-php/app/public/index.php ?

If yes, i can't because i have one website running on my domain, in which i need to implement this virgil security HIPPA, please let me know how to proceed here, 

thanks in advance

**Comment by PetrenkoAnton** [comment]
@Govind13100 , Hi!

You can add **/sample-backend-php** to the exceptions in the main access file.
And add your own access file to the **/sample-backend-php** directory.

Or use subdomain for the generation of your jwt (for example: www.jwt.mydomain.com).

Thanks

**Comment by Govind13100** [comment]
@PetrenkoAnton hi,

I am really not getting your point of adding /sample-backend-php to exceptions in the main access file, how can i do that, the only way in my mind is using .htaccess (setting default to /sample-backend-php access). But why we need to do this, can't we simply run the file by using its location path ?


Please suggest something on it.

**Comment by PetrenkoAnton** [comment]
@Govind13100 Hi!

Current sample is build based on the Slim PHP framework.
And it uses its own routing. So main file is **index.php**.

Add **.htaccess** file to the **./sample-backend-php**:
`RewriteEngine On`
`RewriteCond %{REQUEST_FILENAME} !-f`
`RewriteCond %{REQUEST_FILENAME} !-d`
`RewriteRule ^ index.php [QSA,L]`

And exclude this folder in your main (root) **.htaccess** file:
`RewriteCond %{REQUEST_URI} !^/sample-backend-php/?$`

Please try to do this.

Thanks

**Comment by Govind13100** [comment]
@PetrenkoAnton okay thanks, i will try now and let you know

**Comment by Govind13100** [comment]
@PetrenkoAnton hi,

![UNADJUSTEDNONRAW_thumb_2](https://user-images.githubusercontent.com/26818036/59430764-bd627000-8e00-11e9-9cf1-ebac092c1392.jpg)


this is what i got

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,

Please, show me content of our main **.htaccess** file.

Until tomorrow, I will prepare a step-by-step guide (with screenshots) for you in accordance with the current environment: apache server, .htaccess files and our sample in a subfolder.

Thanks

**Comment by Govind13100** [comment]
@PetrenkoAnton hi, thanks 

i will share the main (root) .htaccess file over email, antptrnk@gmail.com is this your email ?

**Comment by PetrenkoAnton** [comment]
@Govind13100 ,
Yes, its my email

Thanks

**Comment by Govind13100** [comment]
@PetrenkoAnton ,

I have sent the mail, pls check and thanks :)

**Comment by Govind13100** [comment]
thank for your help

**Comment by Govind13100** [comment]
Hi there, 

I am not able to generate the virgil token using `/authenticate ` endpoint. It throws 404 error and I am sure that it's .htaccess redirect issues. I tried with the URL you shared for .[htaccess content](http://www.slimframework.com/docs/v3/start/web-servers.html) but the same error is still occurring.  
I have tried every possible solution but no luck yet. I would appreciate it if you could help me out here with some assistance to make this work as due to this I am facing really very hard problems. 

looking for your response and help 

Thank you

**Comment by PetrenkoAnton** [comment]
@Govind13100 

1. `git clone https://github.com/VirgilSecurity/sample-backend-php.git .`
2. `git checkout apache2-fastcgi`
3. `composer install`
4. `cp .env.example .env`
5. Fill .env file
6. Use endpoints `/authenticate` and `/virgil-jwt`

**Comment by techyroots** [comment]
Thanks, it worked for me. I really appreciate your efforts
