### ISSUE TITLE
Unable to add crypto extension

### ISSUE THREAD

**Issue by Rajat117** [VirgilSecurity/sample-backend-php#6]
PHP Warning:  PHP Startup: Unable to load dynamic library 'virgil_crypto_php'  (tried: /usr/local/lib/php/pecl/20180731/virgil_crypto_php (dlopen(/usr/local/lib/php/pecl/20180731/virgil_crypto_php, 9): image not found)

**Comment by Qzich** [comment]
we updated our sdk and it's extensions, so given issue is not relevant now
